language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO==1.4.13
  - DJANGO==1.5.8
  - DJANGO==1.6.5
matrix:
  exclude:
    - python: 3.3
      env: DJANGO==1.4.13
    - python: 3.4
      env: DJANGO==1.4.13
before_script:
  - "./before_script.sh"
install:
  - pip install $DJANGO
  - pip install .
script:
  - make test
notifications:
  email: false
